{% set name = "asyncer" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/asyncer-{{ version }}.tar.gz
  sha256: a589d980f57e20efb07ed91d0dbe67f1d2fd343e7142c66d3a099f05c620739c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - python >={{ python_min }}
    - anyio >=3.4.0,<5.0
    - typing_extensions >=4.8.0

test:
  imports:
    - asyncer
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tiangolo/asyncer
  summary: Asyncer, async and await, focused on developer experience.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
    - janjagusch
