schema_version: 1

context:
  name: asyncer
  version: "0.0.9"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/asyncer-${{ version }}.tar.gz
  sha256: 9d1d5d688dbf7b3aec182bbf7d4b24ed2f242c727fefab44197c1862a2bb8601

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pdm-backend
    - pip
  run:
    - python >=${{ python_min }}
    - anyio >=3.4.0,<5.0
    - typing_extensions >=4.8.0

tests:
  - python:
      imports:
        - asyncer
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: Asyncer, async and await, focused on developer experience.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/tiangolo/asyncer

extra:
  recipe-maintainers:
    - maresb
    - janjagusch
